### PR TITLE
Fix/readme repo template

### PR DESCRIPTION
**Pull request by GuillaumeFalourd**
### Description

The README template used for creating new formulas repositories needed an update due to broken link and deprecated sections.

### How to verify it

Create a new repository using Ritchie `rit create formula` command.

### Changelog

Fix README repo template.

### CODE REVIEW

**Review by brunasilvazup — APPROVED** [review]

**Review by kaduartur — APPROVED** [review]

**Review by kaduartur — CHANGES_REQUESTED** [review]
You have edited a README.md for integration tests only. I think you need to edit this [README.md](https://github.com/ZupIT/ritchie-formulas/blob/master/templates/create_formula/root/README.md)

**Comment by GuillaumeFalourd** [comment]
Great point Kadu, I'll update this one as well 👍🏼

**Comment by GuillaumeFalourd** [comment]
Done: https://github.com/ZupIT/ritchie-formulas/pull/336

**Comment by brunasilvazup** [comment]
in QA it's fine.

**Review by kaduartur — APPROVED** [review]
LGTM 🚀

**Pull request merged**
