### PR TITLE
Add stdin validation for docker execution

### PR DESCRIPTION
**Pull request by GuillaumeFalourd**
Signed-off-by: GuillaumeFalourd <guillaume.falourd@zup.com.br>

**- What I did**

- Validate if the stdin flag has been used when running a command with Docker.

**- How to verify it**

- Building locally and executing the following command :

```bash
echo '{"input_text":"Dennis", "input_bool":"false", "input_list":"everything", "input_password":"Ritchie"}' | ./rit demo hello-world --stdin --docker
```

**- Description for the changelog**

- Validate if the stdin flag has been used when running a command with Docker.

### CODE REVIEW

**Review by lucasdittrichzup — APPROVED** [review]

**Review by brunasilvazup — CHANGES_REQUESTED** [review]
We have a pr in qa that will change a lot about the runner > https://github.com/ZupIT/ritchie-cli/pull/480
I recommend that you wait and assess whether the error will persist.

**Comment by GuillaumeFalourd** [comment]
> We have a pr in qa that will change a lot about the runner > #480
> I recommend that you wait and assess whether the error will persist.

I've checked the PR @brunasilvazup and this problem hasn't been resolved there. 
It's related to the args defined when running docker and the feature implemented by @kaduartur didn't update that section.

**Review by kaduartur — APPROVED** [review]
LGTM!

**Review by brunasilvazup — APPROVED** [review]
Tested in qa, the error has been fixed :+1:

**Pull request merged**
