### PR TITLE
refactor: remove emojis

### PR DESCRIPTION
**Pull request by DittrichLucas**
**- What I did**

- Remove emojis from sentences because `cmd` and `powershell` are not displayed correctly

cmd

**- How to verify it**

- Run `rit build formula`

**- Description for the changelog**
- Remove emojis from sentences because `cmd` and `powershell` are not displayed correctly

### CODE REVIEW

**Review by victor-schumacher — DISMISSED** [review]

**Review by victorschumacherzup — DISMISSED** [review]

**Review by brunasilvazup — APPROVED** [review]

**Comment by henriquemoraes8** [comment]
Can you add on the description why it is necessary to remove the emojis?

**Review by henriquemoraes8 — APPROVED** [review]

**Review by henriquemoraeszup — APPROVED** [review]

**Pull request merged**
