### PR TITLE
Fixing windows installer and logo

### PR DESCRIPTION
**Pull request by henriquemoraeszup**
Signed-off-by: Henrique Moraes <henrique.moraes@zup.com.br>

**- What I did**
Created a branch based on #555 and fixed the logo layout. The PR also contemplates a fix on the uninstall option of the installer

- How to verify it
Download the QA version.

Install Ritchie in another path and try to remove this with the Windows **uninstall or change a program **
- Description for the changelog
Edit Windows installer template

Captura de Tela (2)
Captura de Tela (3)

### CODE REVIEW

**Review by lucasdittrichzup — DISMISSED** [review]

**Review by victor-schumacher — DISMISSED** [review]

**Comment by henriquemoraeszup** [comment]
please?

**Review by victor-schumacher — APPROVED** [review]

**Review by lucasdittrichzup — APPROVED** [review]

**Pull request merged**
