### PR TITLE
test: github testify

### LINKED ISSUE #792: Tests with Testify in Pkg/Git/Github
**What would you like to be added**:
- [x] Github
- [x] Repository

**Why is this needed**:

### PR DESCRIPTION
**Pull request by lucasdittrichzup**
### Description
This pr **adds the lib testify to the tests of the github package** _(github and repository)_.

In addition, a refactoring has been added to the github.go and repository.go files to facilitate the development of the tests and, consequently, increase the coverage of the package / project.

Close #792  

### How to verify it
1. `check` the unit testing pipeline

### Changelog
Add testify to the tests of the github package

### CODE REVIEW

**Review by brunasilvazup — APPROVED** [review]
Good refac, congrats :1st_place_medal:

**Review by henriquemoraeszup — APPROVED** [review]

**Pull request merged**
