### PR TITLE
Fixes issue #987, restoring compatibility with Docker Desktop < 2.5.0 on Windows/MacOS and adding compatibility to WSL*

### LINKED ISSUE #987: The fix for issue #914 needs to be improved so that we don't unnecessarily break compatibility with Docker Desktop <2.5.0 and also that we support running inside WSL* on Windows
The fix for issue #914 needs to be improved so that we don't unnecessarily break compatibility with Docker Desktop <2.5.0 and also that we support running inside WSL on Windows

**What happened**:

Using the latest versions of Ritchie with the fix for #914, the Docker Runner is unnecessarily broken with Docker Desktop <2.5.0 or within WSL* environments

**What you expected to happen**:

The Docker Runner should normally run in both scenarios.

**How to reproduce it (as minimally and precisely as possible)**:

Try running any Formula on Windows/MacOS with the Docker Runner and Docker Desktop < 2.5.0 installed. Also, on Windows, try the same thing within WSL* but with the latest Docker Desktop versions.

**Anything else we need to know?**:

**Environment**:
- Ritchie version: 2.11.3
- Operating System: Windows/MacOS

### PR DESCRIPTION
**Pull request by dcominottim**
### Description

Fixes issue #987.

### How to verify it

Follow the instructions on #987.

### Changelog

Adds logic to properly switch between 'docker' and 'com.docker.cli' binary names as needed according to the environment.

---------------------------------------------

### This pull request generated the following artifacts.
To test the health and quality of this implementation, download the respective binary for your operating system, unzip and directly run the binary like the examples below.
- **Windows**
 Download the file: **[rit-windows.zip](https://github.com/ZupIT/ritchie-cli/suites/3137824385/artifacts/72033686)**
 Unzip to some folder like: `C:\home\user\downloads\pr989`
 Access the folder: `cd C:\home\user\downloads\pr989`
 Directly call the binary: `.\rit.exe --version` or `.\rit.exe name of formula`
 

 - **Linux**
 Download the file: **[rit-linux.zip](https://github.com/ZupIT/ritchie-cli/suites/3137824385/artifacts/72033684)**
 Unzip to some folder like: `/home/user/downloads/pr989`
 Access the folder: `cd /home/user/downloads/pr989`
 Assign execute permission to binary: `chmod +x ./rit`
 Directly call the binary: `./rit --version` or `./rit name of formula`
 

 - **MacOS**
 Download the file: **[rit-macos.zip](https://github.com/ZupIT/ritchie-cli/suites/3137824385/artifacts/72033685)**
 Unzip to some folder like: `/home/user/downloads/pr989`
 Access the folder: `cd /home/user/downloads/pr989`
 Assign execute permission to binary: `chmod +x ./rit`
 Directly call the binary: `./rit --version` or `./rit name of formula`

> Generated at Thu Jul 01 2021 20:17:29 GMT+0000 (Coordinated Universal Time)

### CODE REVIEW

**Comment by GuillaumeFalourd** [comment]
Do you a way to check these scenarios using automated tests (for example with github actions)?

**Comment by dcominottim** [comment]
> Do you have a way to check these scenarios using automated tests (for example with github actions)?

Hi, @guilhermenasszup! Unfortunately, I am not aware of any way to invoke Docker commands in an Action workflow. The only kind of Docker usage I know that works is running the Action itself within a Docker containers, but here we want to interact with the Docker daemon itself, which I doubt will ever be a supported workflow because of security reasons. I can say I've tested the changes in my local machine -- would be nice to have a second person testing them.

**Comment by dcominottim** [comment]
We could do this in CircleCI, but I don't have access yet (have requested it).

**Comment by dcominottim** [comment]
Another possibility -- that would allow us to still use GitHub Actions -- would consist of using a self-hosted runner, but we won't be able to set this up without several days or weeks of discussion about the infrastructure concerns, costs, and so on.

https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

**Review by fabianofernandeszup — APPROVED** [review]

**Comment by GuillaumeFalourd** [comment]
Thank you @dcominottim 👍🏼  
We'll check the implementation is working as expected on different OS and then merge it and open an ISSUE to create those scenarios using automated tests in the future.

**Comment by dcominottim** [comment]
> Thank you @dcominottim 👍🏼
> We'll check the implementation is working as expected on different OS and then merge it and open an ISSUE to create those scenarios using automated tests in the future.

Thanks a lot, @GuillaumeFalourd and @fabianofernandeszup. You guys rock!

**Review by GuillaumeFalourd — APPROVED** [review]
👍🏼

**Pull request merged**
