### PR TITLE
Add multiselect option

### LINKED ISSUE #600: Add a multiselect input type for formulas
**What would you like to be added**:

I would like to see a new input type to allow selecting more than one option for a same input.

**Why is this needed**:

Today, there is only 3 types: `text`, `bool`, `password`, and be can use the `list` field to give options for the user to choose. However, you can only choose one item on the list at the moment, it would be great to be able to select more than one option for some inputs when necessary.

**Implementation Details**

This feature is already available in the lib survey that is used in the cli. Then just implement a new type of content for the config.json inputs called multiselect.

The behavior will be similar to the list type, but using this multiselect feature.

Example:
https://github.com/AlecAivazis/survey#multiselect

image

### PR DESCRIPTION
**Pull request by rafaeelaudibert**
**- What I did**
**[WIP]** Added multiselect option to Ritchie
Closes #600 

**- How to verify it**

**- Description for the changelog**

Added multiselect option to Ritchie

### CODE REVIEW

**Comment by rafaeelaudibert** [comment]
I am having trouble trying to work around the code. I added the basic interface and integration with the survey library, but didn't understand where I should connect this code to, so that I can handle incoming 'multiselect' types of formulas

**Comment by GuillaumeFalourd** [comment]
> I am having trouble trying to work around the code. I added the basic interface and integration with the survey library, but didn't understand where I should connect this code to, so that I can handle incoming 'multiselect' types of formulas

@rafaeelaudibert : as you're adding a new input type, the first place to update should be the inputs.go class : https://github.com/ZupIT/ritchie-cli/blob/master/pkg/formula/runner/inputs.go . Then, you should check where methods from this class are being used and analyze what should be updated (implementation + tests).

**Comment by henriquemoraeszup** [comment]
Just to provide extra context, when you run `rit formula create` you create a formula with a `config.json` file in which you can define the interactive inputs. The file guillaume mentioned is responsible for reading the config during a formula execution and prompting the user with the correct form

**Comment by rafaeelaudibert** [comment]
Oh, I'm sorry, I've clearly gone in the wrong way. Will try to work on it some more (in the right place this time 😄 ) and will come back with an improved PR (in this same one actually, I'll just rebase it). Thanks!

**Comment by GuillaumeFalourd** [comment]
Hi @rafaeelaudibert , how are you doing ?

Are you still working on this ISSUE ?

**Comment by rafaeelaudibert** [comment]
Hi @GuillaumeFalourd, how are you?

Sadly, I won't have the time to finish this issue right now (end of semester at uni).

I might work this in the future, but not in a close one. Feel free to close this, if anybody else is interested in the issue.
Thanks for the help!

**Comment by GuillaumeFalourd** [comment]
No problem @rafaeelaudibert , I believe the Ritchie Core Team will work on it then, and once you'll be available to contribute again, feel free to work on another ISSUE available on our repositories 👍🏼 

Thank you again for your interest about Ritchie 🚀

**Pull request closed without merging**
