### PR TITLE
Detect new repository version

### PR DESCRIPTION
**Pull request by kaduartur**
### Description
Detect new repository version using the `lastest_version` field in repositories.json file and if the `cache` field was expired get the latest version in git.

image

### How to verify it
You can add a repository with an old version and check if Ritchie shows the new version when executing the `rit` command.

### Changelog
Detect new repo version using cache

### CODE REVIEW

**Review by GuillaumeFalourd — APPROVED** [review]
👏🏼

**Review by lucasdittrichzup — APPROVED** [review]

**Review by brunasilvazup — APPROVED** [review]

**Comment by brunasilvazup** [comment]
Tests in QA it's OK.

**Pull request merged**
