### PR TITLE
fixing release pipeline

### PR DESCRIPTION
**Pull request by viniciusramosdefaria**
### Description

Pipeline fix

### How to verify it
See if in the next release cycle the stable.txt file and ritchie.msi is correct

### Changelog

Adding $ to fix regex match

### CODE REVIEW

**Review by kaduartur — APPROVED** [review]
You are gods! :godmode:

**Comment by henriquemoraeszup** [comment]
Does merging into qa impact anything? 😅

**Comment by henriquemoraeszup** [comment]
Congrats guys 👏

**Comment by brunasilvazup** [comment]
> Does merging into qa impact anything?

Not really, I just did it for "protocol".

**Pull request merged**
