### PR TITLE
Ritchie cmd use

### PR DESCRIPTION
**Pull request by fabianofernandeszup**
### Description
Env to run rit cli using another cmd use

### How to verify it
Run rit with env `RITCHIE_CMD_USE` with other path name inside the user home dir.

Like: 

``` bash
export RITCHIE_CMD_USE=.other-name
rit
```

### Changelog
Added RITCHIE_CMD_USE env to change string cmd use.

---------------------------------------------

### This pull request generated the following artifacts.
To test the health and quality of this implementation, download the respective binary for your operating system, unzip and directly run the binary like the examples below.
- **Windows**
 Download the file: **[rit-windows.zip](https://github.com/ZupIT/ritchie-cli/suites/3677341238/artifacts/89526588)**
 Unzip to some folder like: `C:\home\user\downloads\pr1026`
 Access the folder: `cd C:\home\user\downloads\pr1026`
 Directly call the binary: `.\rit.exe --version` or `.\rit.exe name of formula`
 

 - **Linux**
 Download the file: **[rit-linux.zip](https://github.com/ZupIT/ritchie-cli/suites/3677341238/artifacts/89526586)**
 Unzip to some folder like: `/home/user/downloads/pr1026`
 Access the folder: `cd /home/user/downloads/pr1026`
 Assign execute permission to binary: `chmod +x ./rit`
 Directly call the binary: `./rit --version` or `./rit name of formula`
 

 - **MacOS**
 Download the file: **[rit-macos.zip](https://github.com/ZupIT/ritchie-cli/suites/3677341238/artifacts/89526587)**
 Unzip to some folder like: `/home/user/downloads/pr1026`
 Access the folder: `cd /home/user/downloads/pr1026`
 Assign execute permission to binary: `chmod +x ./rit`
 Directly call the binary: `./rit --version` or `./rit name of formula`

> Generated at Fri Sep 03 2021 16:10:49 GMT+0000 (Coordinated Universal Time)

### CODE REVIEW

**Review by GuillaumeFalourd — APPROVED** [review]
👍🏼

**Review by lucasdittrichzup — APPROVED** [review]

**Comment by GuillaumeFalourd** [comment]
@fabianofernandeszup , please update your branch from the `v3` branch to run the tests again.

**Review by GuillaumeFalourd — CHANGES_REQUESTED** [review]
The #1029  PR needs to be merged before updating this branch from v3 and running the tests again:

**Review by GuillaumeFalourd — APPROVED** [review]
👍🏼

**Pull request merged**
