### PR TITLE
Multiselect flag support

### LINKED ISSUE #791: Tests with Testify in Pkg/Formula
**What would you like to be added**:
- [ ] Formula

**Why is this needed**:

### LINKED ISSUE #881: Flags do not support multiselect
**What happened**:
When adding a multiselect input, it is not read on the `--help` flag and the user cannot use it as argument 

**What you expected to happen**:
After adding a `multiselect` input on `config.json` the formula should support that input

**How to reproduce it (as minimally and precisely as possible)**:
Add a multiselect block and call `--help` on that formula

**Anything else we need to know?**:

**Environment**:
- Ritchie version (use `rit --version`):
- Operating System:
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

### PR DESCRIPTION
**Pull request by henriquemoraeszup**
### Description

When adding a `multiselect` input, Ritchie could not translate it into flags. We need to take this case into account

* Adds support to `list` input type command
* Adds support to `list` input type input
* Adds support to `multiselect` input type command
* Adds support to `multiselect` input type input
* Refactors tests on `formula` package
* Makes a forward-compatible solution for flag reading by extracting any new types as string

Closes #881 
Closes #791 

### How to verify it
Add a `multiselect` input and run `--help`, the input should be listed

### Changelog

Supporting flags for multiselect input

### CODE REVIEW

**Review by GuillaumeFalourd — APPROVED** [review]
🚀

**Review by brunasilvazup — APPROVED** [review]
:top:

**Review by lucasdittrichzup — APPROVED** [review]

**Review by lucasdittrichzup — APPROVED** [review]

**Pull request merged**
