### PR TITLE
Fix/windows package

### PR DESCRIPTION
**Pull request by kaduartur**
**- What I did**
I fixed templates for the Windows installer 

**- How to verify it**
Download the [QA ](http://qa-repo.ritchiecli.io/2.0.0-qa/installer/ritchiecli.msi) version.
- Install Ritchie in another path and try to remove this with the Windows **uninstall or change a program **

**- Description for the changelog**
Edit Windows installer template

### CODE REVIEW

**Review by erneliojuniorzup — DISMISSED** [review]

**Review by lucasdittrichzup — DISMISSED** [review]

**Review by lucasdittrichzup — APPROVED** [review]

**Review by victor-schumacher — APPROVED** [review]

**Comment by henriquemoraeszup** [comment]
Continued on #574

**Pull request closed without merging**
