### PR TITLE
Changing conditional to only return an error when the conditional input variable does not exist in the config.json variable list

### PR DESCRIPTION
**Pull request by andressaabreuzup**
Signed-off-by: Finzi <andressa.abreu@zup.com.br>

### Description
Formulas with nested conditional inputs were returning an unnecessary error.
When there were two flows of nested conditionals, for example, consequently one of them was not satisfied. But an error was returned when the variables of the alternative flow conditionals were tested.  The error said that such variables did not exist, however, they existed. They just weren't being filled by belonging to that other flow that didn't happen.

### How to verify it
Test nested conditional inputs with a alternative flow. (Not a error)
Test conditional inputs that not exists. (A error)

### Changelog
Changing conditional  to only return an error when the conditional input variable does not exist in the config.json variable list

### CODE REVIEW

**Review by henriquemoraeszup — APPROVED** [review]
Hey @andressaabreuzup ! Nice description, thank you. Really helped understand the problem. I am good to go but it seems there is a lint problem 😄

**Comment by andressaabreuzup** [comment]
> Hey @andressaabreuzup ! Nice description, thank you. Really helped understand the problem. I am good to go but it seems there is a lint problem 😄

It was a spacing problem, I fixed it, now it's 100% :)

**Review by brunasilvazup — APPROVED** [review]
:+1:

**Pull request merged**
