### PR TITLE
New ritchiecli-user.msi

### PR DESCRIPTION
**Pull request by kaduartur**
### Description
Create ritchiecli-user.msi without privileges to install

### How to verify it
When you start the ritchie-cli installation using `ritchiecli-user.msi` the Windows system does not need admin permission.

### Changelog
Create new ritchiecli-user.msi

### CODE REVIEW

**Review by GuillaumeFalourd — APPROVED** [review]
👍🏼

**Review by henriquemoraeszup — APPROVED** [review]
Question, this will work both for the community and Itau?

**Review by brunasilvazup — APPROVED** [review]
:+1:

**Comment by kaduartur** [comment]
> Question, this will work both for the community and Itau?

Yes, the `ritchiecli.msi` and` ritchiecli-user.msi` will work for the community, but only` ritchiecli-user.msi` will work for Itaú.

**Pull request merged**
