### PR TITLE
Add tests with testify for delete repo

### PR DESCRIPTION
**Pull request by fernandobelettizup**
### Description

Adding tests with testify for `delete repo`.
### How to verify it
Check created tests on `pkg/cmd/delete_repo_test.go`.
### Changelog

Adding tests with testify for `delete repo`.

### CODE REVIEW

**Review by GuillaumeFalourd — APPROVED** [review]
LGTM 👍🏼

**Review by henriquemoraeszup — APPROVED** [review]

**Review by brunasilvazup — APPROVED** [review]

**Review by lucasdittrichzup — APPROVED** [review]

**Comment by fernandobelettizup** [comment]
\merge qa

**Comment by lucasdittrichzup** [comment]
\merge qa

**Pull request merged**
